swagger: '2.0'
info:
  title: smoothie-api
  description: Send me Smoothies
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
x-google-management:
  metrics:
    - name: "list-smoothies-request"
      displayName: "List smoothie quota"
      valueType: INT64
      metricKind: DELTA
    - name: "order-smoothie-request"
      displayName: "Order smoothie quota"
      valueType: INT64
      metricKind: DELTA
  quota:
    limits:
      - name: "list-smoothie-limit"
        metric: "list-smoothies-request"
        unit: "1/min/{project}"
        values:
          STANDARD: 2
      - name: "order-smoothie-limit"
        metric: "order-smoothie-request"
        unit: "1/min/{project}"
        values:
          STANDARD: 2
paths:
  /listSmoothies:
    get:
      summary: Get the best smoothies
      consumes:
      - application/json
      operationId: listSmoothies
      x-google-backend:
        address: https://us-central1-api-gateway-demo-456905.cloudfunctions.net/listSmoothies 
      responses:
        '200':
          description: Successful response
          schema:
            type: string
      security:
      - api_key: []
      x-google-quota:
        metricCosts:
          "list-smoothies-request": 1
  /orderSmoothie:
    post:
      summary: Order a wonderful smoothie
      consumes:
      - application/json
      operationId: orderSmoothie
      x-google-backend:
        address:  https://us-central1-api-gateway-demo-456905.cloudfunctions.net/orderSmoothie
      responses:
        '200':
          description: Successful response
          schema:
            type: string
      security:
      - api_key: []
      x-google-quota:
        metricCosts:
          "list-smoothies-request": 1
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
